language: node_js

node_js:
  - 'stable'

env:
  - PORT=5003

services:
  - mongodb

script:
  - npm ci
  - npm test:coveralls
  - npm run cover
 notifications:
   email: false
after_success:
  - npm run coveralls
